name: build-and-test-application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
    
    - name: Install app dependencies
      working-directory: ./app
      run: flutter pub get
    
    - name: Run tests
      working-directory: ./app
      run: flutter test
    
    - name: Build for 
      working-directory: ./app
      run: flutter build web
