name: build-and-test-application
on: 
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    defaults:
      run:
        working-directory: ./app
        
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.19.3'
        channel: 'stable'
    
    - name: Install app dependencies
      run: flutter pub get
    
    - name: Run tests
      run: flutter test
    
    - name: Build for web
      run: flutter build web

    - name: Add changes
      run: git add -f ./build/web/ 

    - name: Commit changes
      run: git commit -m "Deploy"
    
    - name: Add credentials
      run: git config --global user.email "rajwolchapagain@gmail.com"
      run: git confgi --global user.name "Rajwol Chapagain"
    
    - name: Push changes
      run: git push origin gh-pages