name: build-and-test-application
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.16.9'
        channel: 'stable'
      working-directory: ./app
    - run: flutter pub get
    - run: flutter test
    - run: flutter build web
